# Generated by Django 6.0.1 on 2026-01-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='monto_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que contaste físicamente en el cajón', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
