# Generated by Django 6.0.1 on 2026-01-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(help_text='Código de barras o interno', max_length=50, unique=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Avisa cuando queda poco')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Devolución)'), ('SALIDA', 'Salida (Venta/Pérdida/Robo)')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
