# Generated by Django 6.0.1 on 2026-01-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, help_text='Escanee el código aquí', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(help_text='Código interno (Ej: MAT-001)', max_length=50, unique=True),
        ),
    ]
