# Generated by Django 6.0.1 on 2026-01-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('DEBITO', 'Tarjeta de Débito'), ('CREDITO', 'Tarjeta de Crédito'), ('QR', 'QR / Billetera Virtual'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
    ]
